default: &default
  adapter: postgresql
  username: housing_su
  password: housing
  su_username: housing_su
  su_password: housing
  database : 'scrum_hammer_development'
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  username: housing_su
  password: housing
  su_username: housing_su
  su_password: housing
  database : 'scrum_hammer_development'
  pool: 5
  timeout: 5000
